require("plugins/rocks-config")
require("plugins/lsp-zero-config")
require("plugins/conform-config")
require("plugins/treesitter-config")
require("plugins/barbar-config")
require("plugins/lualine-config")
require("plugins/comment-nvim-config")
require("plugins/telescope-config")
require("plugins/nvim-tree-config")

require("keymap-config")
require("options")

require("oil").setup()
require("nvim-autopairs").setup()
require("neogit").setup()
