require("packer-config")
require("truezen-config")
require("keymap-config")
require("options")
require("autopairs-config")
require("lualine-config")
require("barbar-config")
require("nvim-tree-config")
require("toggleterm-config")
require("comment-nvim-config")
require("colorizer-config")
require("indent-blankline-config")
require("startup-config")
require("telescope-config")
require("treesitter-config")
--[[ require("catppuccin-config") ]]
require("neogit-config")
require("gitsigns-config")
require("diffview-config")

require("neorg-config")

require("mason-config")
require("lsp-config.lsp")
require("lsp-config.lsp")
require("lsp-config.lspsaga")
require("lsp-config.completion")
require("lsp-config.null-ls")
