require("packer-config")
require("truezen-config")
require("options")
require("keymap-config")
require("autopairs-config")
require("lualine-config")
require("barbar-config")
-- require("colors-config.nightfox")
require("nvim-tree-config")
require("toggleterm-config")
require("comment-nvim-config")
require("colorizer-config")
require("indent-blankline-config")
-- require("shade-config")
require("startup-config")
require("telescope-config")
require("treesitter-config")
require("neorg-config")
require("lsp-config.language-servers")
require("lsp-config.lspsaga")
require("lsp-config.completion")
require("lsp-config.null-ls")
