# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

[plugins]
"rocks.nvim" = "2.19.1" # rocks.nvim can also manage itself :D
neorg = "8.4.0"
"oil.nvim" = "2.7.0"
"rocks-config.nvim" = "1.2.3"
nvim-treesitter = "0.9.2"
tree-sitter-lua = "scm"
tree-sitter-python = "scm"
"mason-lspconfig.nvim" = "1.27.0"
"lualine.nvim" = "scm"
telescope = "0.6.0"
"rocks-git.nvim" = "1.3.1"
nvim-web-devicons = "0.99"
"comment.nvim" = "0.8.0"
nvim-autopairs = "scm"
neogit = "scm"
tree-sitter-typescript = "scm"
tree-sitter-javascript = "scm"
tree-sitter-css = "scm"
tree-sitter-html = "scm"
tree-sitter-bash = "scm"
"mason.nvim" = "1.10.0"
"conform.nvim" = "5.6.0"

[plugins."barbar.nvim"]
git = "romgrk/barbar.nvim"
rev = "v1.7.0-beta.4"

[plugins."nvim-tree.lua"]
git = "nvim-tree/nvim-tree.lua"
rev = "v1.3^{}"

[plugins."lsp-zero.nvim"]
git = "VonHeikemen/lsp-zero.nvim"

[config]
plugins_dir = "plugins/"
auto_setup = false

[treesitter]
auto_highlight = [
	"lua",
	"toml",
]
