return {
	require("plugins.vimtex"),
	require("plugins.autopairs"),
	require("plugins.diffview"),
	require("plugins.colorizer"),
	require("plugins.comment"),
	require("plugins.conform"),
	require("plugins.dashboard"),
	require("plugins.gruvbox-material"),
	require("plugins.octo"),
	-- require("plugins.nightfox"),
	require("plugins.lualine"),
	require("plugins.render-markdown"),
	require("plugins.neorg"),
	require("plugins.neogit"),
	-- require("plugins.nvim-tree"),
	require("plugins.oil"),
	require("plugins.tailwindcss-colorizer-cmp"),
	require("plugins.telescope"),
	require("plugins.treesitter"),
	require("plugins.neogit"),
	require("plugins.lspzero"),
}
